
@host = https://localhost:7231

Content-Type: application/json

{
      
     "id":1,
     "name": "Password1",
     "description":"Description",
     "objection": "Objection"
}

GET {{host}}/deal-managemen/deals
Content-Type: application/json

{
}
 

